language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
script:
  - npm run lint src
  - npm test
  - npm run build
env:
  - SERVER_ADDRESS=https://speech-dismantler.herokuapp.com/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master